### ISSUE TITLE
How can I use the function of advanced data table in SB Admin 2.0?

### ISSUE THREAD

**Issue by javck** [start-laravel/sb-admin-laravel-5#3]
I found that the SB Admin 2.0 has the advanced data table function in table tab.
But I try to use it in the laravel 5.0 version , no luck.
Is any reason can't I use the function?
How can I do if I really need the function?

![2015-05-01_02-47-21](https://cloud.githubusercontent.com/assets/1000675/7420164/d2ebfe4c-efac-11e4-8f23-7dc1430e4bb8.png)

**Comment by sankhadeeproy007** [comment]
SB Admin 2.0 uses a jQuery table plugin for the advanced data tables. Check https://datatables.net/ for the documentation.
