### ISSUE TITLE
Newer Version of laravel 5

### ISSUE THREAD

**Issue by ThamrinPH** [start-laravel/sb-admin-laravel-5#6]
can you make the newer version please, when i tried to intregrated yours with laravel 5.3 i got confused because the structure quite diffrent

and i'm quite new in this,

**Comment by ThamrinPH** [comment]
Nevermind, already got it, thank you

**Comment by deleugpn** [comment]
You could share how you did. I'm going through this right now for Laravel 5.4

**Comment by sandervanhooft** [comment]
> You could share how you did. I'm going through this right now for Laravel 5.4

@deleugpn: anything to share?

**Comment by deleugpn** [comment]
@sandervanhooft I don't remember exactly what was the problem, but I got these 3 files: 

![screenshot](https://puu.sh/vuIv0/d3372e93cf.png)

And then I set webpack: 

```
mix.copy('node_modules/font-awesome/fonts', 'public/fonts');
mix.copy('resources/assets/css/', 'public/css');
mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .less('resources/assets/less/sb-admin-2/sb-admin-2.less', 'public/css')
    .less('node_modules/font-awesome/less/font-awesome.less', 'public/css');
```

**Comment by csernikmarton** [comment]
I’ve just forked this project and updated the dependencies to work with Laravel 5.4.
If you’re still interested, check it out at [https://github.com/csernikmarton/sb-admin-laravel-5](https://github.com/csernikmarton/sb-admin-laravel-5)
