### ISSUE TITLE
Not compatible with php 7.0

### ISSUE THREAD

**Issue by denniseilander** [start-laravel/sb-admin-laravel-5#8]
Hi, thanks for the great template, it looks realy nice!

There is one problem. When I'm running this project on localhost using xampp, I get the following error:

`GET http://localhost:8000/assets/stylesheets/styles.css net::ERR_INVALID_HTTP_RESPONSE` 
`GET http://localhost:8000/assets/scripts/frontend.js net::ERR_INVALID_HTTP_RESPONSE`
`GET http://localhost:8000/favicon.ico net::ERR_INVALID_HTTP_RESPONSE`

With this error, the stylesheets and javascripts won't be loaded, so nothing is working.

When I'm running the project on PHP 5.6 it all works fine. 
Maybe there is a compatibilty bug?

**Comment by deleugpn** [comment]
That has nothing to do with PHP version. These errors just tells us that your files are not visible through the web server.
